version: "3.9"

services:

 nginx:
  image: nginx:1.23.1
  ports:
   - 8021:80
  volumes:
   - ./frontend/dist:/usr/share/nginx/html
  environment:
   - VITE_HOCUSPOCUS_PROVIDER_URL='ws://backend:2300/collaboration'
  depends_on:
   - backend
