version: "3.9"

services:
 postgres:
  image: postgres:14.5
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: postgres
   POSTGRES_DB: docsplus
  ports:
   - '5432:5432'
  volumes:
   - database-data:/var/lib/postgresql/data/
  restart: always

 redis:
  image: redis:alpine
  restart: unless-stopped
  ports:
   - '6389:6379'

 backend:
  restart: always
  build: ./packages/hocuspocus.server
  depends_on:
   - postgres
   - redis
  links:
   - redis
  environment:
   HOCUSPOCUS_EXT_DB_TYPE: PostgreSQL
   DATABASE_URL: postgresql://postgres:postgres@postgres:5432/docsplus?schema=public
   APP_PORT: 2300
   REDIS: "true"
   REDIS_HOST: redis
   REDIS_PORT: 6379
  ports:
   - 8002:2300

volumes:
 database-data:
