version: "3.9"

services:
 postgres:
  image: postgres:14.5
  environment:
   POSTGRES_USER: ${PG_USER}
   POSTGRES_PASSWORD: ${PG_PASSWORD}
   POSTGRES_DB: ${PG_DB}
  ports:
   - '${PG_PORT}:${PG_PORT}'
  volumes:
   - database-data:/var/lib/postgresql/data/
  restart: always

 redis:
  image: redis:alpine
  restart: unless-stopped
  ports:
   - '6389:6379'

 backend:
  restart: always
  build: .
  depends_on:
   - postgres
   - redis
  links:
   - redis
  environment:
   HOCUSPOCUS_EXT_DB_TYPE: PostgreSQL
   APP_PORT: 2300
   REDIS: "true"
   REDIS_HOST: redis
   REDIS_PORT: 6379
  ports:
   - 8002:2300

volumes:
 database-data:
